version: '3.5'

services:
  db:
    container_name: postgres_container
    image: postgres:alpine3.18
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
       - ./postgres-data:/data/postgres
    ports:
      - "5432:5432"

  example-app:
    container_name: example_container
    build: .
    image: example_node_app
    ports:
      - "3000:3000"
    depends_on:
      - db

  dbmigration:
    container_name: postgres_migration_container
    build:
      context: .
      dockerfile: ./migrate.dockerfile
    restart: on-failure
    environment:
      APP_DATABASE_HOST: db
      APP_DATABASE_PORT: 5432
      APP_DATABASE_NAME: postgres
      APP_DATABASE_USER: ${POSTGRES_USER:-postgres}
      APP_DATABASE_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
    depends_on:
      - db